dic_urls = {
        '1':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=81-3%2C81-4%2C81-2%2C81-1&varasTreeSelection.text=4+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 621,
            'nr_registros': 16398,
            'done': True,
            'name': 'Adamantina'
        },
        '2':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=515-2%2C515-1&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 9103,
            'done': True,
            'name': 'Rosana'
        },
        '3':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=83-1%2C83-2&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 13255,
            'done': True,
            'name': 'Aguai'
        },
        '4':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=35-1%2C35-101&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 6713,
            'done': True,
            'name': 'Agua de Lindoia'
        },
        '5':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=58-2%2C58-1%2C58-9&varasTreeSelection.text=3+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 9197,
            'done': True,
            'name' : "Agudos"
        }
,
        '6':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=42-1%2C42-9%2C42-2&varasTreeSelection.text=3+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 6913,
            'done': True,
            'name' : "Altinopolis"
        }
,
        '7':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=526-2%2C526-7%2C526-6%2C526-3%2C526-1%2C526-6808&varasTreeSelection.text=6+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 25703,
            'done': True,
            'name' : "Salto"
        }
,
        '8':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=531-1%2C531-2&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 7256,
            'done': True,
            'name' : "Santa Adelia"
        }
,
        '9':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=19-4%2C19-2%2C19-8%2C19-6%2C19-10%2C19-1%2C19-5%2C19-12%2C19-11%2C19-3&varasTreeSelection.text=10+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 56953,
            'done': True,
            'name' : "Americana"
        },
        '10':{
            'url': "http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=533-6105%2C533-4%2C533-3%2C533-12%2C533-7%2C533-8%2C533-6%2C533-2&varasTreeSelection.text=8+Registros+selecionados&dadosConsulta.ordenacao=DESC",
            'init': 1,
            'nr_registros': 31476,
            'done': True,
            'name' : "Santa Barbara do Oeste"
        },
        '11':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=22-904%2C22-3%2C22-2%2C22-1%2C22-5%2C631-1&varasTreeSelection.text=6+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 18179,
            'done': True,
            'name': 'Amparo',
        },
        '12':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=534-2%2C534-1&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 4902,
            'done': True,
            'name': 'Santa Branca',
        },
        '13':{
            'url':'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=24-2%2C24-1%2C24-5%2C24-3%2C24-4%2C24-6589&varasTreeSelection.text=6+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 27132,
            'done': True,
            'name': 'Andradina',
        },
        '14':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=25-2%2C25-101&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 9876,
            'done': True,
            'name': 'Angatuba',
        },
	'15':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do;jsessionid=A799EA8C50C86BBEE7395818E2086AEC.cjpg1?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=538-2%2C538-1&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 8644,
            'done': True,
            'name': 'Santa Cruz das Palmeiras',
        },
	'16':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=539-2%2C539-11%2C539-1%2C539-4%2C539-3%2C539-12%2C539-9%2C539-13%2C539-14&varasTreeSelection.text=9+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 14627,
            'done': True,
            'name': 'Santa Cruz do Rio Pardo',
        },
	'17':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=28-2%2C28-1%2C28-3&varasTreeSelection.text=3+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 9529,
            'done': True,
            'name': 'Aparecida',
        },
	'18':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=541-5%2C541-6807%2C541-1%2C541-3%2C541-2&varasTreeSelection.text=5+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 29073,
            'done': True,
            'name': 'Santa Fe do Sul',
        },
	'19':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=30-1%2C30-2&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 6747,
            'done': True,
            'name': 'Apiai',
        },
	'20':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=543-2%2C543-3%2C543-6%2C543-1&varasTreeSelection.text=4+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 12994,
            'done': True,
            'name': 'Santa Isabel',
        },
	'21':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=32-15%2C32-14%2C32-16%2C32-7%2C32-12%2C32-26%2C32-3%2C32-6890%2C32-8%2C32-6%2C32-4%2C32-2%2C32-9%2C32-5%2C32-1%2C509-1&varasTreeSelection.text=16+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 240,
            'nr_registros': 69346,
            'done': True,
            'name': 'Aracatuba',
        },
	'22':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=547-4%2C547-2%2C547-7128&varasTreeSelection.text=3+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 12445,
            'done': True,
            'name': 'Santa Rita do Passa Quatro',
        },
	'23':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=37-23%2C37-22%2C37-15%2C37-7%2C37-12%2C37-1%2C37-2%2C37-3%2C37-4%2C37-5%2C37-6%2C37-14%2C37-17%2C37-8%2C37-9%2C37-6918&varasTreeSelection.text=16+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 85278,
            'done': True,
            'name': 'Araraquara',
        },
	'24':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=549-1%2C549-2&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 5642,
            'done': True,
            'name': 'Santa Rosa de Viterbo',
        },
    '25':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do;jsessionid=8B96A0FF8F3860AFC20E5A9EAADBF520.cjpg1?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=38-10%2C38-11%2C38-12%2C38-7%2C38-8%2C38-501%2C38-907&varasTreeSelection.text=7+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 40226,
            'done': True,
            'name': 'Araras',
        },
    '26':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=529-8%2C529-2%2C529-7%2C529-1&varasTreeSelection.text=4+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 9901,
            'done': True,
            'name': 'Santana de Parnaiba',
        },
    '27':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=553-2%2C553-1&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 14434,
            'done': True,
            'name': 'Santo Anastacio',
        },
    '28':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=554-5%2C554-19%2C554-14%2C554-1%2C554-11%2C554-10%2C554-4%2C554-13%2C554-29%2C554-21%2C554-6%2C554-8%2C554-23%2C554-24%2C554-9%2C554-25%2C554-3%2C554-26%2C554-7%2C554-22%2C554-12%2C554-2&varasTreeSelection.text=22+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 122202,
            'done': True,
            'name': 'Santo Andre',
        },
    '29':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=47-1%2C47-3%2C47-4%2C47-2%2C47-6%2C47-9%2C47-5%2C47-10%2C47-6523%2C47-901&varasTreeSelection.text=10+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 32834,
            'done': True,
            'name': 'Assis',
        },
    '30':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=48-7%2C48-9%2C48-15%2C48-11%2C48-18%2C48-6889%2C48-14%2C48-12%2C48-6895%2C48-13&varasTreeSelection.text=10+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 35873,
            'done': True,
            'name': 'Atibaia',
        },
    '31':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=562-18%2C562-27%2C562-8%2C562-13%2C562-14%2C562-9%2C562-22%2C562-23%2C562-1%2C562-3%2C562-5%2C562-20%2C562-12%2C562-10%2C562-25%2C562-2%2C562-30%2C562-7169%2C562-11%2C562-7165%2C562-40%2C562-21%2C562-16%2C562-7%2C562-15%2C562-31%2C562-24%2C562-28%2C562-35%2C562-26%2C562-19%2C562-37%2C562-36%2C562-29%2C158-1&varasTreeSelection.text=35+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 4919,
            'nr_registros': 244387,
            'done': True,
            'name': 'Santos',
        },
    '32':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do;jsessionid=06190B96FCD328FCAC07447CBC98F7B6.cjpg1?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=60-2%2C60-6&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 6144,
            'done': True,
            'name': 'Auriflama',
        },
    '33':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=563-2%2C563-1&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 3013,
            'done': True,
            'name': 'Sao Bento do Sapucai',
        },
    '34':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=564-5%2C564-19%2C564-20%2C564-6%2C564-9%2C564-15%2C564-23%2C564-21%2C564-14%2C564-7148%2C564-12%2C564-4%2C564-11%2C564-10%2C564-2%2C564-17%2C564-22%2C564-3%2C564-13%2C564-7%2C564-8%2C564-16%2C564-18%2C564-27&varasTreeSelection.text=24+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 140349,
            'done': True,
            'name': 'Sao Bernardo do Campo',
        },
    '35':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=565-5%2C565-1%2C565-4%2C565-10%2C565-7%2C565-2%2C565-3%2C565-903%2C565-13%2C565-8%2C565-6&varasTreeSelection.text=11+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 43065,
            'done': True,
            'name': 'Sao Caetano do Sul',
        },

    '36':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=73-501%2C73-5%2C73-502%2C73-6899%2C73-10%2C73-11%2C73-7&varasTreeSelection.text=7+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 32720,
            'done': True,
            'name': 'Avare',
        },
    '37':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=555-1%2C566-7148%2C566-9%2C566-2%2C566-7147%2C566-3%2C566-10%2C566-1%2C566-13%2C566-11%2C566-7%2C566-5%2C566-4&varasTreeSelection.text=13+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 75770,
            'done': True,
            'name': 'Sao Carlos',
        },
    '38':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=568-7143%2C568-7146%2C568-9%2C568-5%2C568-7144%2C568-7145&varasTreeSelection.text=6+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 22732,
            'done': True,
            'name': 'Sao Joao da Boa Vista',
        },
    '39':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=59-1%2C59-2&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 3442,
            'done': True,
            'name': 'Bananal',
        },

    '40':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=572-7144%2C572-2%2C572-101%2C572-3&varasTreeSelection.text=4+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 20612,
            'done': True,
            'name': 'Sao Joaquim da Barra',
        },
    '41':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=62-1%2C62-2%2C62-6892&varasTreeSelection.text=3+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 11383,
            'done': True,
            'name': 'Bariri',
        },
     '42':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=63-2%2C63-3%2C63-1&varasTreeSelection.text=3+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 19289,
            'done': True,
            'name': 'Barra Bonita',
        },
      '43':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=575-2%2C575-3%2C575-5%2C575-1&varasTreeSelection.text=4+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 16631,
            'done': True,
            'name': 'Sao Jose do Rio Pardo',
        },
    '44':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=520-2%2C577-12%2C577-7188%2C577-7%2C577-16%2C577-7187%2C577-29%2C577-10%2C577-5%2C577-28%2C577-9%2C577-18%2C577-23%2C577-19%2C577-24%2C577-7186%2C577-11%2C577-6%2C577-8%2C577-7183%2C577-22%2C577-1%2C577-2%2C577-21%2C577-20%2C577-3%2C577-4&varasTreeSelection.text=27+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 211276,
            'done': False,
            'name': 'Sao Jose dos Campos',
        },
    '45':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=66-1%2C66-3%2C66-2%2C66-4%2C66-6904%2C66-9%2C66-5%2C66-7%2C66-901&varasTreeSelection.text=9+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 60020,
            'done': False,
            'name': 'Barretos',
        },
    '46':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=579-1%2C579-2&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 4169,
            'done': True,
            'name': 'São Luiz do Paraitinga',
        },
    '47':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=68-9%2C68-6%2C68-2%2C68-3%2C68-6916%2C68-901%2C68-12%2C68-11%2C68-1%2C68-4%2C68-10%2C68-5&varasTreeSelection.text=12+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 123519,
            'done': True,
            'name': 'Barueri',
        },
    '48':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=581-8%2C581-3%2C581-1%2C581-2&varasTreeSelection.text=4+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 11537,
            'done': False,
            'name': 'São Manuel',
        },
    '49':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=70-11%2C70-10%2C70-501%2C70-8%2C70-1%2C70-6911&varasTreeSelection.text=6+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 17354,
            'done': False,
            'name': 'Batatais',
        },
    '50':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=582-2%2C582-1&varasTreeSelection.text=2+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 4830,
            'done': True,
            'name': 'Sao Miguel Arcanjo',
        },
    '51':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=1-9%2C1-6888%2C1-201%2C1-702%2C1-205%2C1-202%2C1-501%2C1-3%2C1-7%2C1-8%2C1-4%2C1-6%2C1-502%2C1-321%2C1-6893%2C1-1%2C1-2%2C1-204%2C1-203%2C1-5&varasTreeSelection.text=20+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 145541,
            'done': True,
            'name': 'Foro Regional I Santa, Sao Paulo',
        },
    '52':{
            'url': 'http://esaj.tjsp.jus.br/cjpg/pesquisar.do?conversationId=&dadosConsulta.pesquisaLivre=&tipoNumero=UNIFICADO&numeroDigitoAnoUnificado=&foroNumeroUnificado=&dadosConsulta.nuProcesso=&dadosConsulta.nuProcessoAntigo=&classeTreeSelection.values=&classeTreeSelection.text=&assuntoTreeSelection.values=&assuntoTreeSelection.text=&agenteSelectedEntitiesList=&contadoragente=0&contadorMaioragente=0&cdAgente=&nmAgente=&dadosConsulta.dtInicio=&dadosConsulta.dtFim=&varasTreeSelection.values=2-6870%2C2-6872%2C2-501%2C2-5%2C2-1%2C2-6862%2C2-3%2C2-204%2C2-6878%2C2-6876%2C2-6874%2C2-901%2C2-202%2C2-7%2C2-14%2C2-15%2C2-6868%2C2-205%2C2-101%2C2-201%2C2-6%2C2-6875%2C2-4%2C2-2%2C2-6873%2C2-502%2C2-6871%2C2-6867%2C2-102%2C2-6865%2C2-13%2C2-6869%2C2-6866%2C2-203%2C2-8%2C2-321&varasTreeSelection.text=36+Registros+selecionados&dadosConsulta.ordenacao=DESC',
            'init': 1,
            'nr_registros': 306509,
            'done': True,
            'name': 'Foro Regional II Santo Amaro, Sao Paulo',
        },
    '53':{
            'url': '',
            'init': 1,
            'nr_registros': 0,
            'done': True,
            'name': '',
        },
}

def nr_paginas(nr_regs):
    return int(nr_regs/15)
